apiVersion: v1
kind: Service
metadata:
  name: educycle-frontend
  labels:
    app: educycle-frontend
spec:
  selector:
    app: educycle-frontend
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
  type: ClusterIP
