apiVersion: v1
kind: Service
metadata:
  name: educycle-backend
  labels:
    app: educycle-backend
spec:
  selector:
    app: educycle-backend
  ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP
  type: ClusterIP
