apiVersion: apps/v1
kind: Deployment
metadata:
  name: educycle-postgres
  labels:
    app: educycle-postgres
spec:
  replicas: 1
  selector:
    matchLabels:
      app: educycle-postgres
  template:
    metadata:
      labels:
        app: educycle-postgres
    spec:
      containers:
        - name: postgres
          image: postgres:16
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_DB
              valueFrom:
                configMapKeyRef:
                  name: educycle-config
                  key: POSTGRES_DB
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: educycle-secret
                  key: SPRING_DATASOURCE_USERNAME
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: educycle-secret
                  key: SPRING_DATASOURCE_PASSWORD
          volumeMounts:
            - name: postgres-data
              mountPath: /var/lib/postgresql/data
      volumes:
        - name: postgres-data
          persistentVolumeClaim:
            claimName: educycle-postgres-pvc
