apiVersion: v1
kind: Secret
metadata:
  name: educycle-secret
type: Opaque
stringData:
  SPRING_DATASOURCE_USERNAME: educycle
  SPRING_DATASOURCE_PASSWORD: change_me
  JWT_SECRET: change_me_to_a_long_random_secret
