#!/usr/bin/env bash
# =============================================================================
#  EduCycle – Continuous Dev: Auto Semantic Version Bump
#  Trigger: GitHub Action on every push to dev
# =============================================================================
set -euo pipefail

# ── Config ────────────────────────────────────────────────────────────────────
CODEBASE="${GITHUB_WORKSPACE:-$(pwd)}"
DEV_BRANCH="dev"
COMMIT_TYPES="feat|fix|BREAKING CHANGE|refactor|docs|build|style|perf"

# ── Setup git identity (required for CI) ─────────────────────────────────────
git config user.name  "Auto Commit Bot"
git config user.email "bot@educycle.dev"

# ── 1. Ensure we are on dev and up-to-date ───────────────────────────────────
cd "${CODEBASE}"
git checkout "${DEV_BRANCH}"
git pull origin "${DEV_BRANCH}"

# ── 2. Get current version ───────────────────────────────────────────────────
CURRENT_TAG=$(git describe --tags --abbrev=0 2>/dev/null || echo "v0.0.0")
CURRENT_NUM="${CURRENT_TAG#v}"
IFS='.' read -r MAJOR MINOR PATCH <<< "${CURRENT_NUM}"

echo "📌 Current version: ${CURRENT_TAG}"

# ── 3. Extract commit type from latest commit message ────────────────────────
LAST_MSG=$(git log -1 --pretty=%s)
LAST_COMMIT_TYPE=$(echo "${LAST_MSG}" | grep -oE "${COMMIT_TYPES}" | head -1 || echo "fix")

echo "🔍 Detected commit type: ${LAST_COMMIT_TYPE}"

# ── 4. Bump semantic version ──────────────────────────────────────────────────
if [[ "${LAST_MSG}" =~ "BREAKING CHANGE" ]]; then
  MAJOR=$((MAJOR + 1))
  MINOR=0
  PATCH=0
  BUMP_TYPE="MAJOR"
elif [[ "${LAST_COMMIT_TYPE}" == "feat" ]]; then
  MINOR=$((MINOR + 1))
  PATCH=0
  BUMP_TYPE="MINOR"
else
  # fix, refactor, docs, build, style, perf → patch bump
  PATCH=$((PATCH + 1))
  BUMP_TYPE="PATCH"
fi

NEXT_VERSION="v${MAJOR}.${MINOR}.${PATCH}"
echo "🚀 Next version: ${NEXT_VERSION} (${BUMP_TYPE} bump)"

# ── 5. Skip if this commit is already a meta-bump (avoid infinite loop) ──────
if echo "${LAST_MSG}" | grep -q "^ci: bump version to v"; then
  echo "⏭️  Last commit was already a version bump — skipping."
  exit 0
fi

# ── 6. Write version to VERSION file ─────────────────────────────────────────
echo "${NEXT_VERSION}" > VERSION
git add VERSION

# ── 7. Commit version bump ───────────────────────────────────────────────────
git commit -m "ci: bump version to ${NEXT_VERSION} (${LAST_COMMIT_TYPE})" \
           -m "Auto-generated by continuous-dev pipeline." \
           --allow-empty

# ── 8. Tag the bump commit ────────────────────────────────────────────────────
git tag -a "${NEXT_VERSION}" -m "Version ${NEXT_VERSION} – auto-tagged on dev"

# ── 9. Push commit + tag ─────────────────────────────────────────────────────
git push origin "${DEV_BRANCH}"
git push origin "${NEXT_VERSION}"

echo "✅ Done — ${NEXT_VERSION} committed and tagged on ${DEV_BRANCH}."
