-- =============================================================
-- EduCycle Backend V1 baseline
-- Target DB: PostgreSQL
--
-- Scope: ADR 0001 core marketplace contract.
-- Kept: auth/user/profile, listing/category, transaction HTTP messages,
-- review, admin-lite support, and persisted notifications used by core flows.
-- Excluded from baseline: AI/RAG, book-wanted, wishlist, media-only features,
-- and WebSocket-only persistence.
-- =============================================================

CREATE EXTENSION IF NOT EXISTS "pgcrypto";

-- =====================
-- USERS
-- =====================
CREATE TABLE users (
    id                              UUID         NOT NULL DEFAULT gen_random_uuid(),
    username                        VARCHAR(100) NOT NULL,
    email                           VARCHAR(200) NOT NULL,
    password_hash                   TEXT         NOT NULL,
    role                            VARCHAR(20)  NOT NULL DEFAULT 'USER',
    avatar                          TEXT,
    bio                             TEXT,
    created_at                      TIMESTAMPTZ  NOT NULL DEFAULT NOW(),

    google_id                       VARCHAR(255),
    facebook_id                     VARCHAR(255),
    microsoft_id                    VARCHAR(255),

    is_email_verified               BOOLEAN      NOT NULL DEFAULT FALSE,
    email_verification_token        TEXT,
    email_verification_token_expiry TIMESTAMPTZ,

    password_reset_token            TEXT,
    password_reset_token_expiry     TIMESTAMPTZ,

    phone                           VARCHAR(20),
    phone_verified                  BOOLEAN      NOT NULL DEFAULT FALSE,

    refresh_token                   VARCHAR(200),
    refresh_token_expiry            TIMESTAMPTZ,
    refresh_token_family            UUID,

    notify_product_moderation       BOOLEAN      NOT NULL DEFAULT TRUE,
    notify_transactions             BOOLEAN      NOT NULL DEFAULT TRUE,
    notify_messages                 BOOLEAN      NOT NULL DEFAULT TRUE,
    transaction_rules_accepted_at   TIMESTAMPTZ,
    trading_allowed                 BOOLEAN      NOT NULL DEFAULT TRUE,

    CONSTRAINT pk_users PRIMARY KEY (id),
    CONSTRAINT uq_users_email UNIQUE (email),
    CONSTRAINT chk_users_role CHECK (role IN ('USER', 'ADMIN'))
);

CREATE INDEX idx_users_refresh_token
    ON users (refresh_token)
    WHERE refresh_token IS NOT NULL;

-- =====================
-- LISTING
-- =====================
CREATE TABLE categories (
    id   INTEGER GENERATED BY DEFAULT AS IDENTITY,
    name VARCHAR(100) NOT NULL,

    CONSTRAINT pk_categories PRIMARY KEY (id)
);

CREATE TABLE products (
    id            UUID          NOT NULL DEFAULT gen_random_uuid(),
    name          VARCHAR(200)  NOT NULL,
    description   TEXT,
    price         NUMERIC(18,2) NOT NULL,
    image_url     TEXT,
    image_urls    TEXT,
    category      VARCHAR(100),
    condition     VARCHAR(100),
    contact_note  TEXT,
    category_id   INTEGER,
    user_id       UUID          NOT NULL,
    status        VARCHAR(20)   NOT NULL DEFAULT 'PENDING',
    reject_reason TEXT,
    created_at    TIMESTAMPTZ   NOT NULL DEFAULT NOW(),

    CONSTRAINT pk_products PRIMARY KEY (id),
    CONSTRAINT fk_product_user
        FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE,
    CONSTRAINT fk_product_category
        FOREIGN KEY (category_id) REFERENCES categories (id) ON DELETE SET NULL,
    CONSTRAINT chk_products_status
        CHECK (status IN ('PENDING', 'APPROVED', 'REJECTED', 'SOLD')),
    CONSTRAINT chk_products_price_non_negative CHECK (price >= 0)
);

CREATE INDEX idx_products_status ON products (status);
CREATE INDEX idx_products_user_id ON products (user_id);
CREATE INDEX idx_products_category_id ON products (category_id);

-- =====================
-- TRANSACTIONS
-- =====================
CREATE TABLE transactions (
    id               UUID          NOT NULL DEFAULT gen_random_uuid(),
    product_id       UUID          NOT NULL,
    buyer_id         UUID          NOT NULL,
    seller_id        UUID          NOT NULL,
    amount           NUMERIC(18,2) NOT NULL,
    status           VARCHAR(20)   NOT NULL DEFAULT 'PENDING',
    otp_code         VARCHAR(64),
    otp_expires_at   TIMESTAMPTZ,
    buyer_confirmed  BOOLEAN       NOT NULL DEFAULT FALSE,
    seller_confirmed BOOLEAN       NOT NULL DEFAULT FALSE,
    created_at       TIMESTAMPTZ   NOT NULL DEFAULT NOW(),
    updated_at       TIMESTAMPTZ   NOT NULL DEFAULT NOW(),
    dispute_reason   TEXT,
    disputed_at      TIMESTAMPTZ,
    cancel_reason    TEXT,
    cancelled_at     TIMESTAMPTZ,

    CONSTRAINT pk_transactions PRIMARY KEY (id),
    CONSTRAINT fk_transaction_product
        FOREIGN KEY (product_id) REFERENCES products (id),
    CONSTRAINT fk_transaction_buyer
        FOREIGN KEY (buyer_id) REFERENCES users (id),
    CONSTRAINT fk_transaction_seller
        FOREIGN KEY (seller_id) REFERENCES users (id),
    CONSTRAINT chk_transactions_status
        CHECK (status IN (
            'PENDING',
            'ACCEPTED',
            'MEETING',
            'COMPLETED',
            'AUTO_COMPLETED',
            'REJECTED',
            'CANCELLED',
            'DISPUTED'
        )),
    CONSTRAINT chk_transactions_amount_non_negative CHECK (amount >= 0),
    CONSTRAINT chk_transactions_distinct_parties CHECK (buyer_id <> seller_id)
);

CREATE INDEX idx_transactions_buyer ON transactions (buyer_id);
CREATE INDEX idx_transactions_seller ON transactions (seller_id);
CREATE INDEX idx_transactions_product ON transactions (product_id);
CREATE INDEX idx_transactions_status ON transactions (status);
CREATE INDEX idx_transactions_status_updated_at
    ON transactions (status, updated_at)
    WHERE status IN ('PENDING', 'ACCEPTED');

CREATE TABLE messages (
    id             UUID        NOT NULL DEFAULT gen_random_uuid(),
    transaction_id UUID        NOT NULL,
    sender_id      UUID        NOT NULL,
    content        TEXT        NOT NULL,
    created_at     TIMESTAMPTZ NOT NULL DEFAULT NOW(),

    CONSTRAINT pk_messages PRIMARY KEY (id),
    CONSTRAINT fk_message_transaction
        FOREIGN KEY (transaction_id) REFERENCES transactions (id) ON DELETE CASCADE,
    CONSTRAINT fk_message_sender
        FOREIGN KEY (sender_id) REFERENCES users (id)
);

CREATE INDEX idx_messages_transaction ON messages (transaction_id, created_at);
CREATE INDEX idx_messages_sender ON messages (sender_id);

-- =====================
-- REVIEWS
-- =====================
CREATE TABLE reviews (
    id             UUID        NOT NULL DEFAULT gen_random_uuid(),
    user_id        UUID        NOT NULL,
    product_id     UUID,
    target_user_id UUID,
    transaction_id UUID,
    rating         INTEGER     NOT NULL,
    content        TEXT        NOT NULL,
    created_at     TIMESTAMPTZ NOT NULL DEFAULT NOW(),

    CONSTRAINT pk_reviews PRIMARY KEY (id),
    CONSTRAINT fk_review_user
        FOREIGN KEY (user_id) REFERENCES users (id),
    CONSTRAINT fk_review_product
        FOREIGN KEY (product_id) REFERENCES products (id) ON DELETE CASCADE,
    CONSTRAINT fk_review_target_user
        FOREIGN KEY (target_user_id) REFERENCES users (id),
    CONSTRAINT chk_reviews_rating CHECK (rating BETWEEN 1 AND 5),
    CONSTRAINT chk_reviews_has_target CHECK (product_id IS NOT NULL OR target_user_id IS NOT NULL)
);

CREATE INDEX idx_reviews_user ON reviews (user_id);
CREATE INDEX idx_reviews_product ON reviews (product_id);
CREATE INDEX idx_reviews_target_user ON reviews (target_user_id);
CREATE INDEX idx_reviews_transaction ON reviews (transaction_id);

-- =====================
-- CORE NOTIFICATION SUPPORT
-- =====================
CREATE TABLE notifications (
    id          UUID         NOT NULL DEFAULT gen_random_uuid(),
    user_id     UUID         NOT NULL,
    type        VARCHAR(50)  NOT NULL,
    title       VARCHAR(200) NOT NULL,
    message     TEXT         NOT NULL,
    related_id  UUID,
    is_read     BOOLEAN      NOT NULL DEFAULT FALSE,
    created_at  TIMESTAMPTZ  NOT NULL DEFAULT NOW(),

    CONSTRAINT pk_notifications PRIMARY KEY (id),
    CONSTRAINT fk_notification_user
        FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE
);

CREATE INDEX idx_notifications_user_unread
    ON notifications (user_id, is_read, created_at DESC);

-- =====================
-- SEED DATA
-- =====================
INSERT INTO users (
    id,
    username,
    email,
    password_hash,
    role,
    is_email_verified,
    phone_verified,
    notify_product_moderation,
    notify_transactions,
    notify_messages,
    trading_allowed,
    created_at
) VALUES (
    '00000000-0000-0000-0000-000000000001',
    'admin',
    'admin@educycle.com',
    '$2a$11$rKaPf4vIrVgZqa5Y.uhOnOHwFBsf0wWNk0bP48o9ZdUFZO6j1.1tK',
    'ADMIN',
    TRUE,
    FALSE,
    TRUE,
    TRUE,
    TRUE,
    TRUE,
    '2025-01-01 00:00:00+00'
) ON CONFLICT (id) DO NOTHING;

INSERT INTO categories (id, name) VALUES
    (1, 'Giáo Trình'),
    (2, 'Sách Chuyên Ngành'),
    (3, 'Tài Liệu Ôn Thi'),
    (4, 'Dụng Cụ Học Tập'),
    (5, 'Ngoại Ngữ'),
    (6, 'Khác')
ON CONFLICT (id) DO NOTHING;

SELECT setval(pg_get_serial_sequence('categories', 'id'), 6, true);
